### ISSUE TITLE
Add Code analysis

### ISSUE THREAD

**Issue by abdelhamidbakhta** [PegaSysEng/pantheon#1051]
### Description
As a Developer, I want to have an overview of code quality so that i can follow the evolution of quality across time. 

### Acceptance Criteria
* clear and concrete metrics
* easy to use system (can be run locally)
* online version of the latest stable branch analysis

### Proposal
* use sonarqube analysis
* define quality gate 
* use docker containers to run sonarqube
* use in memory storage for local development
* use persistent (postgres) storage for production
* build pipelines jobs running sonarqube analysis

**Comment by arash009** [comment]
Hi @abdelhamidbakhta 

Thank you for the suggestion. We've previously considered Sonarqube for this purpose and came to the conclusion that our existing spotless and errorprone checks were sufficient to support our current development. As we grow further and have more changes occurring in the codebase we will likely re-evaluate that stance and expand our suite of quality analysis tools.

If there is anything specific with the current spotless and errorprone checking that you would like to see improved please let us know!
