### ISSUE TITLE
Implement EthSubmitWork JSON RPC API

### ISSUE THREAD

**Issue by timbeiko** [PegaSysEng/pantheon#1052]
### Description
Implement the EthSubmitWork JSON-RPC call in Pantheon, as per [the specification in the JSON RPC wiki](https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_submitwork). For similar APIs implemented in Pantheon, see [here](https://github.com/PegaSysEng/pantheon/tree/master/ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods). 

### Acceptance Criteria
* EthSubmitWork API is implemented according to specification linked above;
* Implementation includes test. For tests on similar APIs, see [here](https://github.com/PegaSysEng/pantheon/tree/5f8059d0559509042944488a611bcf554058d41a/ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods). 
* Optional: add documentation for this feature, see the [Contribution Guidelines.](https://github.com/PegaSysEng/pantheon/blob/master/CONTRIBUTING.md#documentation-style-guide)

**Comment by arash009** [comment]
This issue has been moved to [Jira ](https://pegasys1.atlassian.net/browse/PAN-1246)for tracking. Closing in Github.
