### ISSUE TITLE
Implement DebugTraceBlock JSON RPC APIs

### ISSUE THREAD

**Issue by timbeiko** [PegaSysEng/pantheon#1055]
### Description
Implement the DebugTraceBlock JSON-RPC call in Pantheon, which will return a stack trace containing the opcodes called by transactions in the block.  Three variants of the API should be implemented: 

* DebugTraceBlock, which takes in a valid RLP encoding of a block as input; 
  * **Note**, the parent of this block must be present or it will fail. 
* DebugTraceBlockByHash, which takes in the block hash as input; 
* DebugTraceBlockByNumber, which will take the block number as input. 

### Acceptance Criteria
* All three APIs listed above are implemented in Pantheon;
  * Inputs are as defined above;
  * Return is an RLP output, for example: 
```
{
  gas: 999,
  returnValue: "",
  structLogs: [{
      depth: 1,
      error: "",
      gas: 99999,
      gasCost: 2,
      memory: null,
      op: "PUSH1",
      pc: 0,
      stack: [],
      storage: {}
  }
```
* Implementation includes testing;
* Optional: add documentation for this feature, see the [Contribution Guidelines](https://github.com/PegaSysEng/pantheon/blob/master/CONTRIBUTING.md#documentation-style-guide).

### Additional information
For a similar API implemented in Pantheon, see [DebugTraceTransaction](https://github.com/PegaSysEng/pantheon/blob/5f8059d0559509042944488a611bcf554058d41a/ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/DebugTraceTransaction.java) and its [DebugTraceTransactionTest](https://github.com/PegaSysEng/pantheon/blob/5f8059d0559509042944488a611bcf554058d41a/ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/DebugTraceTransactionTest.java).

**Comment by kziemianek** [comment]
Hey, I would love to tackle this issue, can I ?

**Comment by ajsutton** [comment]
@kziemianek That would be fantastic.  Feel free to ask questions here or on Gitter (http://gitter.im/PegaSysEng/pantheon) if you need any pointers.  And feel free to put up draft PRs to get early feedback on the work too.

**Comment by arash009** [comment]
Closing this issue and moving the ticket to Jira for tracking -- [PAN-2506](https://pegasys1.atlassian.net/browse/PAN-2506).

[PR ](https://github.com/PegaSysEng/pantheon/pull/1088)is work in progress
