### ISSUE TITLE
Migrate off of JSR-305 annotations

### ISSUE THREAD

**Issue by timbeiko** [PegaSysEng/pantheon#1068]
### Description
For Java 11 the JSR-305 series of annotations (javax.annotation.*) present several problems, the biggest being tool support in Java 9 and later. We should get off of them. (for a deeper explanation see https://github.com/google/guava/issues/2960#issue-263628666).

We only use two annotations from that family: javax.annotation.Nullable and javax.annotation.concurrent.Immutable.

For Immutable I would recommend the Guava annotation (com.google.errorprone.annotations.Immutable) since the errorprone checker will be looking for that in errorprone version 2.3.2. These appear to have been added to satisfy errorprone prior to the decision by them to abandon JSR 305.

For Nullable, the options are less clear. We should consult with the authors who added those annotations to see what tooling depends on them and pick a tool-compatible option.

### Acceptance Criteria

- All pantheon code is scrubbed of java.annotation.* annotations
- In all cases a suitable and supported annotation is used in its place.
- Existing code quality tools recognize these new annotations where the old annotations were used.

**Comment by arash009** [comment]
This issue is being tracked in [Jira](https://pegasys1.atlassian.net/browse/PAN-1741). Closing in Github.
