### ISSUE TITLE
Implement EthSubmitHashrate JSON RPC API

### ISSUE THREAD

**Issue by timbeiko** [PegaSysEng/pantheon#1093]
### Description
Implement the EthSubmitHashrate API conforming to the [EIP-1474](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1474.md#methods) specification, copied below: 

#### Parameters

|#|Type|Description|
|-|-|-|
|1|{[`Data`](#data)}|hash rate|
|2|{[`Data`](#data)}|random ID identifying this node|

#### Returns

{`boolean`} - `true` if submitting went through successfully, `false` otherwise

#### Example

```sh
# Request
curl -X POST --data '{
    "id": 1337,
    "jsonrpc": "2.0",
    "method": "eth_submitHashrate",
    "params": [
        "0x0000000000000000000000000000000000000000000000000000000000500000",
        "0x59daa26581d0acd1fce254fb7e85952f4c09d0915afd33d3886cd914bc7d283c"
    ]
}' <url>

# Response
{
    "id": 1337,
    "jsonrpc": "2.0",
    "result": true
}
```

**Comment by arash009** [comment]
Closing as moving to Jira: https://pegasys1.atlassian.net/browse/PAN-1247
