### ISSUE TITLE
Implement Web3Sha3 JSON RPC API

### ISSUE THREAD

**Issue by timbeiko** [PegaSysEng/pantheon#1094]
### Description
Implement the Web3Sha3 JSON RPC API as per the [EIP-1474 specification](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1474.md#methods), copied below. 

*Note:* this uses the Keccak-256 algorithm.   

#### Description

Hashes data using the Keccak-256 algorithm

#### Parameters

|#|Type|Description|
|-|-|-|
|1|{[`Data`]()}|data to hash|

#### Returns

{[`Data`]()} - Keccak-256 hash of the given data

#### Example

```sh
# Request
curl -X POST --data '{
    "id": 1337,
    "jsonrpc": "2.0",
    "method": "web3_sha3",
    "params": ["0x68656c6c6f20776f726c64"]
}' <url>

# Response
{
    "id": 1337,
    "jsonrpc": "2.0",
    "result": "0xc94770007dda54cF92009BFF0dE90c06F603a09f"
}
```

**Comment by arash009** [comment]
Closing this as already completed: https://github.com/ConsenSys/pantheon/pull/910
