### ISSUE TITLE
Compression Exceptions should be handled with breach of protocol

### ISSUE THREAD

**Issue by ekellstrand** [PegaSysEng/pantheon#185]
### Description
As a MainNet peer, I want pantheon to to terminate connections with BREACH_OF_PROTOCOL when a compression exception occurs so that the network operates properly.

context: https://github.com/PegaSysEng/pantheon/pull/30#discussion_r224488520

### Acceptance Criteria
* changing CompressionException to a checked exception
* handling it in the Deframer to close the protocol exchanges.

### Versions
* Software version: 0.8.1

**Comment by ajsutton** [comment]
These was resolved a little while back as part of other work. The uncompressed messages turn out to be from an old Parity version which, if the connection timed out waiting for the handshake to complete, would send an uncompressed disconnect message.  More recent version of Parity have been fixed to not send these messages.
