### ISSUE TITLE
Create unit tests for EthGetBlockTransactionCountByNumber

### ISSUE THREAD

**Issue by ekellstrand** [PegaSysEng/pantheon#187]
### Description
As a pantheon developer, I want unit tests for the class listed in the title.

### Acceptance Criteria
- Create unit tests for the class listed in the Title.  Refer to related JSON-RPC classes for examples.

### Versions
* Software version: 0.8.1

**Comment by droconnel22** [comment]
Hello! I am interested in helping Pantheon (yay). Per the guide, this seems to be a good issue to start with. Has some one already started on this issue? Is there any more information worth knowing? Let me know how to best connect and any additional guidelines or suggestions you might have. Thanks!

**Comment by mbaxter** [comment]
Closing this as it appears we already have test coverage for this method.

**Comment by mbaxter** [comment]
@droconnel22 - Adding comments to these issues is one way to get feedback, we also have a gitter channel if you're not getting responses here: https://gitter.im/PegaSysEng/pantheon. And for general information we have docs up here: https://docs.pantheon.pegasys.tech/en/stable/
