### ISSUE TITLE
Create unit tests for EthGetTransactionCount

### ISSUE THREAD

**Issue by ekellstrand** [PegaSysEng/pantheon#188]
### Description
As a pantheon developer, I want unit tests for the class listed in the title.

### Acceptance Criteria
- Create unit tests for the class listed in the Title.  Refer to related JSON-RPC classes for examples.

### Versions
* Software version: 0.8.1

**Comment by strangepowers** [comment]
Is this not already the ethereum/jsonrpc/src/test/java/tech/pegasys/pantheon/ethereum/jsonrpc/internal/methods/EthGetTransactionCountTest.java tests?

**Comment by ajsutton** [comment]
Yes, that covers it. Not sure how that got missed but thanks for pointing it out.
