### ISSUE TITLE
Support the EVMC interface

### ISSUE THREAD

**Issue by axic** [PegaSysEng/pantheon#229]
### Description
As a developer it would be nice to have Pantheon support the [EVMC](https://github.com/ethereum/evmc) interface

The EVMC interface defines an API how Clients and VMs can communicate. It is implemented currently in aleth and geth, while multiple VMs support it, including an [ewasm](https://github.com/ewasm) client.

See also https://github.com/ethereum/evmc/issues/137

**Comment by axic** [comment]
There's some initial work started here: https://github.com/ethereum/evmc/pull/171

**Comment by arash009** [comment]
This issue has been transferred to [Jira ](https://pegasys1.atlassian.net/browse/PAN-2484)for tracking. Closing in Github
