### ISSUE TITLE
How to report to ethstats dashboard?

### ISSUE THREAD

**Issue by 5chdn** [PegaSysEng/pantheon#241]
### Description
As a Node Operator, I want a dashboard so that I can monitor my nodes. 

### Acceptance Criteria
* Reports correct status and version to ethstats

### Steps to Reproduce (Bug)
1. Enable RPC on the Pantheon client
2. Configure an Eth-Net-Intelligence-API client to monitor
3. See the Pantheon nodes are listed as _offline_ even though stats are updated each block

**Expected behavior:** 
- Should look like your presentation at Devcon :D

**Actual behavior:** [What actually happens]
- No version string reported
- Node shows as offline, even though it clearly syncs
- Does not show peer count

**Frequency:** [What percentage of the time does it occur?]
4/4, see http://ethstats.goerli.ethberl.in:3000/

### Versions (Add all that apply)
* Software version: 0.9.0 master @ 9f8512b4c0ce3bdbff83e1f4c038eac0c2546d51
* Java version: openjdk version "1.8.0_181"
* OS Name & Version: DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
* Kernel Version: Linux qa-afri-test-v20794 4.15.0-1030-azure #31~16.04.1-Ubuntu SMP Tue Oct 30 19:40:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by 5chdn** [comment]
![screenshot at 2018-11-07 16-07-24](https://user-images.githubusercontent.com/15729797/48139661-50ee2400-e2a7-11e8-881e-6d9cf4e60541.png)

**Comment by lucassaldanha** [comment]
We have a fork of the eth-net-intelligence-api that we modified to collect the reports. Our plan is to support the “original” eth-net-intelligence collector soon.

You can check the fork here: https://github.com/lucassaldanha/eth-net-intelligence-api

**Comment by lucassaldanha** [comment]
I've opened a PR on eth-net-intelligence-api to be considerate when a client is not mining (https://github.com/cubedro/eth-net-intelligence-api/pull/264).

While this PR is not merged, you can use my fork: https://github.com/lucassaldanha/eth-net-intelligence-api
