### ISSUE TITLE
MainnetBlockBodyValidator | Invalid block: receipts root mismatch

### ISSUE THREAD

**Issue by 5chdn** [PegaSysEng/pantheon#245]
### Description
As an Node, I want Consensus so that I can sync the chain. 

### Acceptance Criteria
* Import block 9554 from the Görli chain (`0x9ba7bbf8487006902c91ded8ed04cf80ad3a6efa6e27d2c53d14f05bc5e235dc`)

### Steps to Reproduce (Bug)
1. Get the Görli genesis https://github.com/goerli/testnet/blob/master/geth/goerli.genesis
2. Sync pantheon with Görli bootnodes https://github.com/goerli/testnet/blob/master/bootnodes.txt
3. Get stuck on a different fork after block 9554 http://ethstats.goerli.ethberl.in:3000/

**Expected behavior:** 
Pantheon should be in consensus with Geth and Parity.

**Actual behavior:**
- ReceiptsRoot Mismatch with Pantheon Clique, ref https://github.com/goerli/testnet/issues/6

```
2018-11-09 10:09:21.055+00:00 | EthScheduler-Workers | WARN  | MainnetBlockBodyValidator | Invalid block: receipts root mismatch (expected=0x3dc2cb692e7b8cd4276e523dfd031960d2e09bc24fcc5ccf990434c697e67d87, actual=0x2aa024623680a960cc38a96838a71e2463b0d182a897f95ea928be00cb5560c9)
2018-11-09 10:09:21.056+00:00 | EthScheduler-Workers | WARN  | PipelinedImportChainSegmentTask | Import of chain segment (9400 to 9600) failed: Failed to import block: 9554, 0x9ba7bbf8487006902c91ded8ed04cf80ad3a6efa6e27d2c53d14f05bc5e235dc.
```

Logs: https://gist.github.com/JohnnySheffield/c3deae0f33d96ec6105a3b5bc2d27060

**Frequency:** [What percentage of the time does it occur?]
Over 9000

### Versions (Add all that apply)
* Software version: master @ 2ee9cb149777ad9ed4612e2dcc2e800d8aea2633
* Java version: openjdk version "1.8.0_181"
* OS Name & Version: Ubuntu 16.04.5 LTS
* Kernel Version: Linux qa-afri-test-v20794 4.15.0-1030-azure #31~16.04.1-Ubuntu SMP Tue Oct 30 19:40:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Additional Information

Interestingly, block 9554 (`0xbffb9f4cc63999eeda597dcc34d6128b22208ae0d151eff6d0bd062b3639c438`) was sealed by a pantheon node.

**Comment by ajsutton** [comment]
Interestingly when I sync to goerli with geth 1.8.14-stable it appears to agree with Pantheon and gets stuck on block 9,555.

```
ERROR[11-11|10:32:19.172]
########## BAD BLOCK #########
Chain config: {ChainID: 6284 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Engine: clique}

Number: 9554
Hash: 0x9ba7bbf8487006902c91ded8ed04cf80ad3a6efa6e27d2c53d14f05bc5e235dc
	&{[] 0 3227777 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [] [245 192 219 30 207 178 147 39 48 19 254 164 173 81 24 16 53 35 117 169 159 34 40 189 243 25 15 224 226 58 238 177] [139 86 80 252 119 33 47 118 80 139 140 105 41 164 194 192 209 65 23 20] 3227777}


Error: invalid receipt root hash (remote: 3dc2cb692e7b8cd4276e523dfd031960d2e09bc24fcc5ccf990434c697e67d87 local: 2aa024623680a960cc38a96838a71e2463b0d182a897f95ea928be00cb5560c9)
```

**Comment by ajsutton** [comment]
But Geth v1.8.17-stable agrees with Parity.

**Comment by ajsutton** [comment]
Ok looks like an SSTORE cost difference.  Pantheon charges 5000 when geth 1.8.17 charges 200.  Geth 1.8.16 includes the change log entry "Add Constantinople net gas store implementation".

Actually the problem is fairly simple - our Clique implementation doesn't support Constantinople.  Fortunately that's an easy fix (and I already have some work in progress to make milestone management reusable across MainNet & Clique.

**Comment by 5chdn** [comment]
Thanks for the quick response. The fix works :+1:  :+1:  :+1:

**Comment by JohnnySheffield** [comment]
@ajsutton can we get this fix pushed to pegasyseng/pantheon docker hub? I'm running a pantheon node on OpenShift and it speeds up the process if i can deploy the image from there.

**Comment by lucassaldanha** [comment]
We should have a new release sometime this week. This includes an updated Docker image 👍🏼
