### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by kurthalex** [PegaSysEng/pantheon#271]
The ropsten genesis file link mentioned [here](https://github.com/PegasysEng/pantheon/wiki/Run-Docker-Image#run-a-node-on-ropsten-testnet) is broken 

[https://github.com/PegasysEng/pantheon/wiki/Run-Docker-Image#run-a-node-on-ropsten-testnet](https://github.com/PegasysEng/pantheon/wiki/Run-Docker-Image#run-a-node-on-ropsten-testnet)

All the links of [this paragraph] (https://github.com/PegasysEng/pantheon/wiki/Private-Network-Quickstart#creating-a-transaction-using-metamask) are also broken

**Comment by NicolasMassart** [comment]
@kurthalex thanks for your feedback. We have the project to change the way the doc works to prevent that, it's a work in progress so we'll fix the wiki first.

**Comment by NicolasMassart** [comment]
Links fixed in the wiki. Thanks @kurthalex for noticing the error.
