### ISSUE TITLE
Clique validator issues

### ISSUE THREAD

**Issue by 5chdn** [PegaSysEng/pantheon#279]
Please excuse that I ignore the issue template. 

I was observing some problematic behaviour of Pantheon Clique validators. Sometimes they "rush" to validate even though it's not their turn. While the resulting blocks are valid as per protocol, the issue here is that it can happen two different validators seal a block with same number and same difficulty at the same time (with different hashes though), this often causes the network to halt as it might happen that the validators cannot agree on which of the two competing blocks to decided on for the canonical chain.

We have this situation in Goerli every now and then, and I think restarting all the validators will allow fixing this issue, maybe. However, discussing this with @karalabe, he told me they have a minor fix in the Geth code available for this. Quoting from Gitter:

> Though what we definitely want to minimize is competing concurrent blocks
> Geth's mining code has explicit delays so if we're mining out of turn, we delay publishing the block by `rand(500 * num_signers)` miliseconds
> This ensure that we don't mine competing blocks that might split the network
> If pantheon is mining but doesn't have this extra clause, then they _will_ constatnly mine competing blocks, so it's down to probabilities as to when te system goes boom (if there's an offline signer)

Could you consider something like this?

**Comment by Errorific** [comment]
Hi @5chdn,
We already have the delay described by @karalabe in place. Could you please provide some more information around the rushed blocks you're seeing. How long the node is waiting before proposing out of turn? Maybe links to the problematic blocks in the Goerli block explorer?

**Comment by 5chdn** [comment]
>  How long the node is waiting before proposing out of turn? 

From what I see, it's not waiting at all. For example, when starting a validator node, it immediately seals a block even if it's not connected to peers yet, or without checking if it's their turn, or if there even is another block sealed yet.

**Comment by rain-on** [comment]
Hi 5chdn,

There are some ways in which the behaviour you're seeing is somewhat expected - specifically if the following steps occurred:

* A pantheon validator is part of a clique network, and is syncing its chain
* The pantheon validator is then stopped for a period of time (greater than block interval)
* The pantheon validator is restarted.

In this instance, the newly restarted Pantheon validator would publish a new block immediately for the following reasons:
1. Its local chain head indicates this node is a validator
2. The timestamp of its local chain chain is more than 'block interval' in the past (Pantheon does its best to make sure timestamps between Clique blocks are as close to 'block interval' as possible). I.e. timestamps are with respect to parentHeader, not node start time.

As the validator has no peers (yet), it is unable to determine that it is behind the global chain head, and must assume that it is up to date, and is required to produce blocks.

**Comment by rain-on** [comment]
@5chdn wondering if this issue is it still causing problems for Goerli?

**Comment by 5chdn** [comment]
I did not see any issues recently. I would, instead of trying to fix this here, push for a 2nd iteration for the Clique engine. 

So let's close this for now and collaborate on Cliquev2 in near future.

**Comment by ajsutton** [comment]
Thanks.  For the benefit of anyone who stumbles across this in the future there's some related discussion going on in the Clique EIP: https://github.com/ethereum/EIPs/pull/1570#discussion_r254203668

An explanation of some of the things that I believe contribute to this type of problem is at 
https://docs.google.com/document/d/1tmsr66sAPJmIZfSy5zck1uxnLzaXYxvzTNL5CF1pJQ0/edit#heading=h.ic4qz2ybx51. (which is also referenced in the EIP discussions and has follow up comments over there).
