### ISSUE TITLE
Doc --host-whitelist added by PR#295

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/pantheon#297]
### Description
Doc `--host-whitelist` and defaulting to localhost if not specified as added by PR#295

### Acceptance Criteria
* `--host-whitelist` added to Command Line Reference
* RPC doc updated to describe how to include localhost in Host header

**Comment by donntrenton** [comment]
Donn reviewed the new content on 12-9.

**Comment by donntrenton** [comment]
Added a few comments in the review doc.

**Comment by MadelineMurray** [comment]
Review rework complete
