### ISSUE TITLE
Test and update RPC Pub/Sub methods

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/pantheon#309]
Test these methods using Simple WebSocket Client:
eth_subscribe
eth_unsubscribe
eth_subscription

And these subscriptions:
newHeads
logs
pendingTransactions
syncing

RPC Pub/Sub doc -> https://github.com/PegaSysEng/pantheon/wiki/RPC-PubSub

**Comment by MadelineMurray** [comment]
Ready for review.  

Review doc - https://docs.google.com/document/d/1mRGcZjx30cXxuMC6aThqNR6YWp73zGjEvU9agRb3bQI/edit 

Slack link - https://consensys.slack.com/archives/GCEHWHAQ2/p1543817039014200

**Comment by donntrenton** [comment]
Started reviewing the review doc and wasn't sure what was updated; we should talk about it.

**Comment by MadelineMurray** [comment]
Review rework completed.
