### ISSUE TITLE
Plan onboarding webinar prerequisites

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/pantheon#318]
### Requirements 
* Define prerequisites required to follow along or complete afterwards (depending on approach) 
* Define steps (including walkthrough docs) to be completed 
* Test process/steps on internal audience (including Grace, Faisal, Vijay, and Arash) 

### Additional Requirements 
Needed by the 18th (test process at least a few days before)

**Comment by donntrenton** [comment]
Reviewing recorded demos:

PegaSys Pantheon Demo (Pre-Alpha)
https://consensys.zoom.us/recording/play/VYBuY5KfrgkLc6PQ3KCpBkgJjWZ7_n3-pEc3d3snPeYH4ofnP6849KxIWl2vEhHH?continueMode=true

PegaSys Pantheon Demo (Alpha Onboarding)
https://consensys.zoom.us/recording/play/NGFBReQms4r9pfGwHszhRa2PPlPFR72uEFPW6XaGK8xUqWAZ8tYQexCQazvW6K_i?continueMode=true

ConsenSysAcademy's Developer Program On-Demand
https://courses.consensys.net/courses/course-v1:ConsenSysAcademy+2+2/

**Comment by donntrenton** [comment]
Let's set up a walkthrough for early next week to do the install / setup / run steps.

**Comment by donntrenton** [comment]
Prerequisites one-pager:

Prerequisites for Running Pantheon
https://docs.google.com/document/d/1TLdNcIU3oCIPDuoby_yzFdpftHzH90WCmF5JBMqlFjs/edit#

**Comment by donntrenton** [comment]
Working with Nico and Chris M to test/debug the new Quickstart on Windows--possibly a Docker issue.
