### ISSUE TITLE
Add chocolatey install option for Windows 

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/pantheon#327]
### Requirements 
Add chocolatey install option for Windows

**Comment by MadelineMurray** [comment]
Ready for review.  Updated Wiki pages: 
https://github.com/PegaSysEng/pantheon/wiki/Install-Binaries
https://github.com/PegaSysEng/pantheon/wiki/Install-Chocolatey

Review doc: 
https://docs.google.com/document/d/1a-UbxAcrZTKypiS8pP3m9bwynM7aQSvS5GwhD5QOpds/edit

Slack link: 
https://consensys.slack.com/archives/GCEHWHAQ2/p1543452706351800

**Comment by donntrenton** [comment]
Donn reviewed Chocolatey Installation content on 12-9 and approved with comments.

**Comment by MadelineMurray** [comment]
Review rework done
