### ISSUE TITLE
New repo (or use zip file) for onboarding webinar files 

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/pantheon#356]
### Requirements 
* Can clone repo (or use zip file) to run private network quickstart using binaries 
* Includes all files required for onboarding seminar

**Comment by donntrenton** [comment]
Reviewed and approved. I've used the new repo PegaSysEng/pantheon-quickstart to run the onboarding demo, and it works fine. I cloned the repo and also downloaded/extracted the ZIP and examined the contents--it contains all the files needed to run the demo.
