### ISSUE TITLE
Outline onboarding webinar steps 

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/pantheon#358]
## Requirements
* Steps to complete for onboarding webinar
* Test by Donn
* Have tested by someone else

**Comment by donntrenton** [comment]
This is being reviewed in meetings with Pliny, Faisal, Grace, and Lucas.

**Comment by donntrenton** [comment]
Revised the webinar workflow and outline with input from the Dec 11 run-through meeting. This has been reviewed.

Also created a separate presenters agenda doc.

We'll present this version today in a dress rehearsal meeting.
