### ISSUE TITLE
admin_peers API documentation

### ISSUE THREAD

**Issue by arash009** [PegaSysEng/pantheon#363]
### Description
As a user, I want to have the admin_peers JSON RPC API documented, so that I know its available and how to use it.

https://github.com/ethereum/go-ethereum/wiki/Management-APIs#admin_peers

### Acceptance Criteria
* admin_peers API documented
* Documentation tested and validated

**Comment by MadelineMurray** [comment]
Question in prod dev.

**Comment by MadelineMurray** [comment]
Review link: 
https://docs.google.com/document/d/1PrlDvAjbPs_E7OHR77dgWVuAmTPtZwbGCfYV3KNSjIA/edit 

Slack link: 
https://consensys.slack.com/archives/GCEHWHAQ2/p1544409794044300

**Comment by MadelineMurray** [comment]
Followed up with Danno/Lucas to check this has actually been reviewed.

**Comment by MadelineMurray** [comment]
Review comments from Donn and Nico approved.

**Comment by MadelineMurray** [comment]
Reviewed by Danno.
