### ISSUE TITLE
Create an Azure Windows 10 instance for test

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/pantheon#366]
### Requirements 
Create an Azure Windows 10 instance for test
Communicate to Pliny team members about how to access for testing

**Comment by NicolasMassart** [comment]
Can't really provide one until we have a proper Azure account

**Comment by NicolasMassart** [comment]
We discussed this during our sprint close and it seems that it won't give us anything to have that as it won't make us able to fully test and it's going to cost money for no real improvement. What we really need is physical windows machines to test Pantheon on. Donn have one and some devs too, so we could rely on them. A CI physical windows server could be nice too.
Meanwhile, adding in the process to have at least windows smoke tests can do the job.
