### ISSUE TITLE
Test pantheon.cli.PantheonCommandTest fails on Windows

### ISSUE THREAD

**Issue by Nashatyrev** [PegaSysEng/pantheon#379]
### Description
Test fails on Windows machine: 
```
> Task :pantheon:test

tech.pegasys.pantheon.cli.PantheonCommandTest > overrideDefaultValuesIfKeyIsPresentInConfigFile FAILED
    org.mockito.exceptions.verification.WantedButNotInvoked at PantheonCommandTest.java:277

72 tests completed, 1 failed, 1 skipped

> Task :pantheon:test FAILED

FAILURE: Build failed with an exception.
```
### Acceptance Criteria
Test should pass

### Steps to Reproduce (Bug)
On Win run the gradle build: 
```
gradlew.bat build
```

**Expected behavior:** 
Build should complete successfully 

**Actual behavior:** 
Build fails

**Frequency:** 
Always

### Versions (Add all that apply)
* Software version: latest master
* OS Name & Version: Windows 10

### Additional Information
The issue relates to backslashes in Windows path

**Comment by Errorific** [comment]
Thanks for the fix @Nashatyrev
