### ISSUE TITLE
eth_estimateGas indicates transaction is added to the blockchain

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/pantheon#387]
eth_estimateGas indicates transaction is added to the blockchain

**Comment by donntrenton** [comment]
Description of original issue (NC-1899):

Description of eth_estimateGas currently includes:
The transaction is added to the blockchain.
I’m pretty sure this isn’t the case and the Geth doc for the same method indicates it’s not added to the blockchain. 
I’m not sure the reference to Etherscan is adding any value and how do we know the ‘gas used’ if this is an estimate? 
Per NC‌-1784 Pantheon doesn’t currently implement the pending block so I’m not sure if the following statement is accurate: 
If you do not specify a gas limit, Pantheon uses the gas limit from the pending block as an upper bound. As a result, the returned estimate might not be enough to execute the call or transaction when the amount of gas is higher than the pending block's gas limit.
The result is described as ‘Amount of gas used’ → shouldn’t it be ‘Amount of gas estimated for transaction’?

**Comment by donntrenton** [comment]
Review doc:
ZH#387 / NC-1899 - eth_estimateGas
https://docs.google.com/document/d/1yplyVFqmPEoK_CWhyJ3NmR2aVbg_YqLi8J1xGLbIbkc/edit#heading=h.km0vexjv2w7

**Comment by MadelineMurray** [comment]
Reviewed - mostly minor comments except the question of what exactly is the pending block if you're a non-mining node?

**Comment by donntrenton** [comment]
Incorporated all review changes from PR#485 and closed.
