### ISSUE TITLE
Create Azure quickstart

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/pantheon#399]
### Description
Create Azure quickstart 

### User Story
As a user wanting to deploy Pantheon on Azure, I want a tutorial/How-to guide that defines the steps to deploy Pantheon on Azure, so that I can have a hosted instance of Pantheon running.

### Acceptance Criteria
- A How-To tutorial that takes a user through the end-to-end steps to get Pantheon on Azure, including:
- Info/link to free Azure instanceSpec/setup of VMManual setup of Pantheon on the VMBasic quickstart and validation

**Comment by MadelineMurray** [comment]
### User Story
As a user wanting to deploy Pantheon on Azure, I want a tutorial/How-to guide that defines the steps to deploy Pantheon on Azure, so that I can have a hosted instance of Pantheon running.

### Acceptance Criteria

A How-To tutorial that takes a user through the end-to-end steps to get Pantheon on Azure, including:
* Info/link to free Azure instance
* Spec/setup of VM
* Manual setup of Pantheon on the VM
* Basic quickstart and validation

**Comment by NicolasMassart** [comment]
created a quickstart release suitable for Azure https://github.com/PegaSysEng/pantheon-quickstart/releases/tag/0.8.3
