### ISSUE TITLE
Update filter methods to indicate they return filter ID hashes 

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/pantheon#424]
### Description
Filter JSON-RPC API methods (`eth_newFilter`) etc return non-sequential transaction hashes not sequential decimal IDs.

**Comment by MadelineMurray** [comment]
Ready for review: 
https://consensys.slack.com/archives/GCEHWHAQ2/p1545104161248300

**Comment by donntrenton** [comment]
Reviewed the doc and approved with edits/comments:

#424 Filter ID Hashes
https://docs.google.com/document/d/1fKKc09_y4X2LOSksVJFG7haQgnd7rn3RPYJnGOm7l-o/edit#
