### ISSUE TITLE
Update contribution guidelines with doc markdown rules

### ISSUE THREAD

**Issue by NicolasMassart** [PegaSysEng/pantheon#435]
Doc is a new part of the main site. Anyone can create a PR to contribute to the docs, so we need guidelines.

**Comment by NicolasMassart** [comment]
The extensions available over default Markdown on our new doc system are defined in the mkdocs.yml file.

Some are shipped with the Material design theme we use https://squidfunk.github.io/mkdocs-material/ some are from the default Markdown Python extensions https://python-markdown.github.io/extensions/#officially-supported-extensions : 
- Admonition : enable nice info/warning/danger blocs
- CodeHilite : highlight keywords in code blocks given the language selected
- Footnotes : add foot notes in the text
- Metadata : manage meta data of the HTML page from within markdown
- Permalinks : generate permalinks for each title in the page
- def_lists : enable easy writing of definition list with only markdown
- toc : to generate ToC from page content
- abbreviation : enable inline abbreviations
- SmartyPants: to use typographic signs like typo quotes

and Python Markdown extensions too https://facelessuser.github.io/pymdown-extensions/ including the following extensions : 

- Arithmatex MathJax : display math formulas
- BetterEm : makes the use of bold and italics easier
- Caret : use inserts and superscript
- Keys : Enable to display computer keys in the text
- Critic : adds markup to show revisions like additions, deletions or highlights
- Details : create collapsible frames
- Emoji : insert emojis in your page, see [Github list of codes which is one of the providers](https://www.webpagefx.com/tools/emoji-cheat-sheet/)
- MagicLink : Support just having html links in the text and also handle Github links like #435
- Mark : enable highlighting text wit double equal sign
- SmartSymbols : to include nive (tm) (c) +/- 1/4 symboles
- SuperFences : code blocs on steroids...
- Tasklist : display lists with checkboxes, nice for supported features list
- Tilde : enable to strike text

 
and we also have third party not official extensions:
- https://github.com/cmacmackin/markdown-include to include content common to multiple pages from other markdown files

**Comment by donntrenton** [comment]
Add a new section titled "Documentation Conventions" to CONTRIBUTING.md. Per conversation with Nico earlier today, here are the topics to cover:

~ Styleguide - MS New Manual of Style + our conventions
~ Markdown - Using Markdown; esp types of Notes and Example tabs
  NO typofgraphic chars (smart quotes, em dash etc) in code examples
~ Links - how to link to other docs
~ Extensions
  [TOC] inserts a TOC of page content on that page
~ Metadata - list mandatory page metadata
description: Pantheon JSON-RPC API methods reference
  
~ Mkdocs - how to install and use mkdocs for doc preview (mandatory step)
~ General writing advice for developers (keep it simple)

**Comment by MadelineMurray** [comment]
Moved to JI
