### ISSUE TITLE
Update Private Network Tutorial to use new quickstart

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/pantheon#448]
### Acceptance Criteria
* Update [Private Network Tutorial](https://pantheon.readthedocs.io/en/latest/Getting-Started/Private-Network-Quickstart/) to use new quickstart at https://github.com/PegaSysEng/pantheon-quickstart
* Test Private Network Tutorial documentation 
* Remove in favour of the new https://github.com/PegaSysEng/pantheon-quickstart

**Comment by donntrenton** [comment]
Build from Source 
https://pantheon.readthedocs.io/en/latest/Installation/Build-From-Source/

change clone from https://github.com/PegaSysEng/pantheon.git -> https://github.com/PegaSysEng/pantheon-quickstart.git


Private Network Quickstart Tutorial
Change the pantheon directory -> the pantheon-quickstart directory
change commands to ./

**Comment by donntrenton** [comment]
Update the commands to use the new pantheon-quickstart repo, the new shell script names, and revise instructions re differences in MacOS vs Windows.

**Comment by donntrenton** [comment]
In Private-Network-Quickstart.md:
~ Reproed and updated steps to use the new pantheon-quickstart repo and new shell scripts
~ Updated notes for Mac and Windows
~ Style and formatting edits
~ Revised text for clarity throughout
~ Opened PR#585 and requested review

**Comment by NicolasMassart** [comment]
In my understanding, this issue also require to remove the old quickstart form repos (and CI pipeline), is it what's planned ?
