### ISSUE TITLE
Document admin_addPeer JSON-RPC method

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/pantheon#465]
### Description
As a user, I want admin_addPeer documented so that I know why and how to use it. 

### Acceptance Criteria
* admin_addPeer documented 
* Use-case included in documentation 
* Documentation tested

**Comment by MadelineMurray** [comment]
Not yet done https://pegasys1.atlassian.net/browse/NC-1970

**Comment by donntrenton** [comment]
Per the dev issue (NC-1970), our implementation of admin_addPeer looks pretty much the same as the corresponding Geth method (https://github.com/ethereum/go-ethereum/wiki/Management-APIs#admin_addpeer).
