### ISSUE TITLE
Document Metrics service flags

### ISSUE THREAD

**Issue by shemnon** [PegaSysEng/pantheon#508]
### Description
As a user, I want metrics export features (#506) documented so that I know what they do. 

* There are two options: `--metrics-enabled` and `--metrics-listen`.  
* These two options work just like `--rpc-enable`/`--ws-enable` and `--rpc-listen`/`--ws-listen`.  
* By default metrics are not exported.  
* When enabled the default port is 127.0.0.1:9545.  
* The metrics server respects the `--host-whitelist` flag for dns rebind attacks protection that `--rpc-*` uses.

### Acceptance Criteria
* Document the `--metrics-enabled` and `--metrics-listen` flags.
* Includes a link to prohetheus (https://prometheus.io/) so that users know what service is intended to interact with.

### Additional Information
We may want to add a sample/operational grafana dashboard.  If so we should open another issue to track this.

**Comment by MadelineMurray** [comment]
Also in acceptance criteria: 
* Add to conceptual content on debugging

**Comment by donntrenton** [comment]
Add reference and conceptual content as follows:

----------
Reference

Pantheon-CLI-Syntax.md:

In the CLI Ref, document the metrics options:

--metrics-enabled
Set to true to enable the Prometheus (https://prometheus.io/) monitoring and alerting service. The default is false.

--metrics-listen
Specifies the host and port on which the Prometheus (https://prometheus.io/) monitoring and alerting service listens. The default is 127.0.0.1:9545. The metrics server respects the --host-whitelist flag for DNS rebind attack protection on RPC.


----------
Conceptual

Using/Debugging.md:

Describe which features of the Prometheus service are used and how to access them. Contact Danno Ferrin (shemnon) to verify the descriptions and for further information on conceptual.

**Comment by donntrenton** [comment]
Madeline and I deleted the old dist and started over. We successfully ran Pantheon with Prometheus. I'll add notes on configuring and running Prometheus so you can view the console and graph to the PR and request review.
