### ISSUE TITLE
Gas limit is irrelevant to eth_estimateGas 

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/pantheon#522]
Currently the description of eth_estimateGas includes:
_If you do not specify a gas amount in the transaction call object, Pantheon uses the gasLimit amount from the block at the head of the chain as the upper limit. If the amount of gas needed is higher than the estimated upper limit, the transaction might not have enough gas to execute._

This is misleading:
* The result for eth_estimateGas is not changed by the gas limit (whether the gas limit comes from the transaction call object or from the chain head) 
* eth_estimateGas doesn't actually execute the transaction

**Comment by donntrenton** [comment]
Mainly clarification: remove the "specify a gas amount" phrase, add a note that eth_estimateGas doesn't execute a transaction, and have a dev review the text.
