### ISSUE TITLE
Metrics: Add and publish a sample Grafana dashboard

### ISSUE THREAD

**Issue by donntrenton** [PegaSysEng/pantheon#535]
### Description

As a user, it would be helpful to be able to access a sample Grafana dashboard on their website (https://grafana.com/dashboards).

Related to #508 Document Metrics service flags

### Acceptance Criteria

* Create a sample operational Grafana dashboard.
* Publish the dashboard on the Grafana website (https://grafana.com/dashboards).
* Our Metrics section in Debugging describes and links to this dashboard.

### Steps to Reproduce (Bug)

N/A

### Versions (Add all that apply)

N/A

### Additional Information

Danno Ferrin suggested this; contact him for details.

**Comment by MadelineMurray** [comment]
Replaced by JI
