### ISSUE TITLE
Test and update command line scenarios in documentation 

### ISSUE THREAD

**Issue by MadelineMurray** [PegaSysEng/pantheon#561]
### Description
As a user, I want scenarios that work as documented. 

### Acceptance Criteria
* All scenarios in documentation using command line options tested 
* All required updates made

**Comment by donntrenton** [comment]
Scenarios that invoke the Pantheon command line:

In **Tutorials**:

Creating a Private Network
https://pantheon.readthedocs.io/en/latest/Tutorials/Create-Private-Network/
(Pantheon invoked 5 times)

In **Configuring**:

Using a Configuration File
https://pantheon.readthedocs.io/en/latest/Configuring-Pantheon/Using-Configuration-File/
(once in "Starting Pantheon with a Configuration File")

Network ID and Chain ID
https://pantheon.readthedocs.io/en/latest/Configuring-Pantheon/NetworkID-And-ChainID/
(once)

Node Keys
https://pantheon.readthedocs.io/en/latest/Configuring-Pantheon/Node-Keys/

Networking
https://pantheon.readthedocs.io/en/latest/Configuring-Pantheon/Networking/
(several options here)

Accounts for Testing
https://pantheon.readthedocs.io/en/latest/Configuring-Pantheon/Accounts-for-Testing/
The test accounts have been tested so many times, I don't believe they need further testing. However, maybe we should test the --genesis command line option in "Genesis File." Also suggest we rename this article to "Test Accounts."

Logging
https://pantheon.readthedocs.io/en/latest/Configuring-Pantheon/Logging/

Testing and Developing Nodes
https://pantheon.readthedocs.io/en/latest/Configuring-Pantheon/Testing-Developing-Nodes/
(3 times)

Proof of Authority
https://pantheon.readthedocs.io/en/latest/Configuring-Pantheon/Proof-of-Authority/
(maybe test the rinkeby.json genesis file?)

Passing JVM Options
https://pantheon.readthedocs.io/en/latest/Configuring-Pantheon/Passing-JVM-Options/
(once)
