### ISSUE TITLE
Add net_services json rpc endpoint

### ISSUE THREAD

**Issue by rojotek** [PegaSysEng/pantheon#625]
The net services endpoint will take in an empty parameter list and return an object containing the list of enabled services (missing keys if the service is not enabled).

Keys for the return object will be:

jsonrpc:
p2p:
ws:
metrics:

Each key will reference an object of the form:
host:
port:

For example:
```
{
  "id":1,
  "jsonrpc": "2.0",
  "result": {
    "jsonrpc": {"host": "127.0.0.1", "port":3000},
    "p2p":{"host": "127.0.0.1", "port":3000},
    "ws":{"host": "127.0.0.1", "port":3000},
    "metrics":{"host": "127.0.0.1", "port":3000}
  }
}
```

in the case where a service is not supported, the key should not exist.

**Comment by dimahledba** [comment]
Do the values can change dynamically during the client execution or can we compute the result only once at startup and directly load the result in memory ?

**Comment by abdelhamidbakhta** [comment]
Do the values can change dynamically during the client execution or can we compute the result only once at startup and directly load the result in memory ?

**Comment by ajsutton** [comment]
The values don't change once Pantheon is running.

**Comment by arash009** [comment]
This issue has been moved to [Jira ](https://pegasys1.atlassian.net/browse/PAN-2485)for tracking. Closing in Github.
