### ISSUE TITLE
Getting CORS errors with  --host-whitelist=* 

### ISSUE THREAD

**Issue by nsavageJVM** [PegaSysEng/pantheon#647]
### Description
As a dev / user, I want to connect via web browser for rpc over http so that I can connect tools like EthStats Lite Explore to a private chain. 

### Acceptance Criteria
*  --host-whitelist=*  works in a browser like firefox or google-chrome

### Steps to Reproduce (Bug)
1. set up a private chain
2. run bootnode like
'../peg/bin/pantheon --datadir=cdata --genesis={path to genesis.json} --network-id 123 --miner-enabled --miner-coinbase=some coinbase --rpc-enabled --ws-enabled  --host-whitelist=* '
3. connect with a tool like EthStats Lite Explore

**Expected behavior:** allows rpc like Curl

**Actual behavior:**  CORS block

**Frequency:** always

### Versions (Add all that apply)
* Software version:latest github master
* Java version: 1.8
* OS Name & Version:Ubuntu 18 minimal
* Kernel Version: Linux ubu-chains 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### Additional Information
Some Raw data
genisis
{

    "config": {
      "chainId": 42,
      "homesteadBlock": 1,
      "eip150Block": 2,
      "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "eip155Block": 3,
      "eip158Block": 3,
      "byzantiumBlock": 4,
      "constantinopleBlock": 5,
      "clique": {
        "blockperiodseconds": 15,
        "epochlength": 30000
      }
    },
    "nonce": "0x0",
    "timestamp": "0x5c368dd7",
    "extraData": "0x00000000000000000000000000000000000000000000000000000000000000008abef4cd9a0d62a5dfe31eb29fa37c3a9e1f782676a80b5f19b34a54e20a76faf86489bd653a900a07877cb169c81a5cdab88a66e753219f3089e2bc0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
    "gasLimit": "0x47b760",
    "difficulty": "0x1",
    "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "coinbase": "0x0000000000000000000000000000000000000000",
    "alloc": {
      "8abef4cd9a0d62a5dfe31eb29fa37c3a9e1f7826": {
        "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
      },
      "76a80b5f19b34a54e20a76faf86489bd653a900a": {
        "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
      },
      "07877cb169c81a5cdab88a66e753219f3089e2bc": {
        "balance": "0x200000000000000000000000000000000000000000000000000000000000000"
      }

    },
    "number": "0x0",
    "gasUsed": "0x0",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"

}

toplogy: 2 nodes and a bootnode
raw data run bootnode with
#!/bin/sh 
../peg/bin/pantheon --datadir=cdata --genesis={path to genisis.json} --network-id 123 --miner-enabled --miner-coinbase=<value fron genisi above> --rpc-enabled --ws-enabled  --host-whitelist=* 
run node like
../peg/bin/pantheon  --datadir=cdata   --genesis={path to genisis.json}  --network-id 123 --bootnodes=enode://{public key}@127.0.0.1:<boot node port> --p2p-listen=127.0.0.1:<node port>

bootnode starts and finds key
2019-01-24 03:16:48.347+03:00 | main | INFO  | KeyPairUtil | Loaded key 0x1b9233eb26672d07fbf23bb8630c75b36d241a538dee15683b3979e78a58f68492630eabfb50ac0756421c06c5700d8beeeedd7f3dfc11ab8069ddfebf86d931 from /home/pathy/chains/private/node1/cdata/key

nodes starts finds key
KeyPairUtil | Loaded key 0x2d8b2adab502cc028e09c347e08f2f3f0de3e2d77bfe016cbb38a32933cf53d1e3997bd82399bc80365c86817d0edac81ef5ad2b796b3970d9a72f5a2236bfd7 from /home/pathy/chains/private/node2/cdata/key

bootnode listens
nioEventLoopGroup-2-1 | INFO  | NettyP2PNetwork | P2PNetwork started and listening on /0:0:0:0:0:0:0:0:30303

nodes listen
nioEventLoopGroup-2-1 | INFO  | NettyP2PNetwork | P2PNetwork started and listening on /0:0:0:0:0:0:0:0:30304

bootnode imports
EthScheduler-Workers | INFO  | BlockPropagationManager | Successfully imported announced block 123 (0x1fe834b5cd5202471739f4da9e741385daa913567037e00659f8bb306da56493) in 19.721ms.

nodes mine
pool-5-thread-5 | INFO  | BlockMiner | Block created, importing to local chain, block includes 0 transactions

curl connects for ws and rpc
browser tool blocks on CORS

**Comment by lucassaldanha** [comment]
Hi,

To add a list of enabled domains for CORS you should use the property `--rpc-cors-origins`. For more information check this link: https://docs.pantheon.pegasys.tech/en/stable/Reference/Pantheon-CLI-Syntax/#rpc-cors-origins

**Comment by lucassaldanha** [comment]
And next time, it might be easier to get an answer on our Gitter channel! :)

https://gitter.im/PegaSysEng/pantheon

**Comment by nsavageJVM** [comment]
thanks
