### ISSUE TITLE
Support of a `trace` Module

### ISSUE THREAD

**Issue by dkrupiza** [PegaSysEng/pantheon#671]
### Description
Hello! Is Pantheon planning to implement a `trace` Module similar to what Parity offers?

**Expected behavior:**
"Module for getting a deeper insight into transaction processing", see https://wiki.parity.io/JSONRPC-trace-module

**Comment by ajsutton** [comment]
Pantheon currently supports the `debug_traceTransaction` API (https://docs.pantheon.pegasys.tech/en/latest/Reference/JSON-RPC-API-Methods/#debug_tracetransaction) which is used by things like the Remix debugger.

At this stage we're not actively working on adding to the trace APIs but we'd definitely be interested in understanding what the needs are for this kind of low level tracing. So, if debug_traceTransaction isn't enough it would be really useful to know what you're trying to do and how you'd usually approach it.

**Comment by ajsutton** [comment]
Hi @dkrupiza just following up on this - have you looked at debug_traceTransaction? Is there anything it doesn't provide that you need?

**Comment by ajsutton** [comment]
Given we don't have any information on the particular use cases to address here I'm going to close this issue. If there are specific uses cases or tools that need additional tracing APIs from Pantheon it would still be great to hear about though.
