### ISSUE TITLE
issue search links in the documentation 

### ISSUE THREAD

**Issue by ekellstrand** [PegaSysEng/pantheon#799]
### Description
As a prospective Pantheon Developer, I want all issue search links in the documentation to include the repo in the path of the URL instead of query string so that github displays the tailored issue search UI.

### Acceptance Criteria
* all issue search links in the **/*.md files to include the repo in the path of the URL instead of query string so that github displays the tailored issue search UI.

### Notes
Replace: ''' https://github.com/search?q=is%3Aopen+is%3Aissue+repo%3APegasysEng%2FPantheon+label%3A%22good%20first%20issue%22 '''
With: ''' https://github.com/PegasysEng/pantheon/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 '''

**Comment by arash009** [comment]
Closing this issue as moving issue tracking to Jira.
