### ISSUE TITLE
JSON-RPC API: Inconsistent Errors When Parameters Are Set to Null

### ISSUE THREAD

**Issue by glethuillier** [PegaSysEng/pantheon#821]
### Description
As a user, I want the JSON-RPC API to systematically and uniformly give me the reason why my request is rejected when I do not provide required parameters so that I can more easily correct my request. 

### Acceptance Criteria
* A JSON-RPC API request containing `"params":[]` (i.e. an empty array) returns a *400 Bad Request* containing a message `"Invalid params"` when the missing parameters are required.
* A JSON-RPC API request containing `"params":null` (i.e. a null object) returns a *400 Bad Request* containing a message `"Invalid params"` when the missing parameters are required.
* A JSON-RPC API request containing `"params":[null]` (i.e. a null array) returns a *400 Bad Request* containing a message `"Invalid params"` when the missing parameters are required.

### Steps to Reproduce
1. `./pantheon --network=dev --miner-enabled --miner-coinbase=0xfe3b557e8fb62b89f4916b721be55ceb828dbd73 --rpc-http-cors-origins="all" --host-whitelist="all" --rpc-ws-enabled --rpc-http-enabled --data-path=/tmp/tmpDatdir`

2. `curl -i -X POST --data '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":[],"id":1}' 127.0.0.1:8545` 

   > HTTP/1.1 400 Bad Request
   > Content-Type: application/json
   > content-length: 108
   >
   > {
   >   "jsonrpc" : "2.0",
   >   "id" : 1,
   >   "error" : {
   >     "code" : -32602,
   >     "message" : "Invalid params"
   >   }
   > }

3. `curl -i -X POST --data '{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":null,"id":1}' 127.0.0.1:8545`

   > HTTP/1.1 500 Internal Server Error
   > content-length: 0

4. `curl -i -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":[],"id":1}' 127.0.0.1:8545` 

   > HTTP/1.1 400 Bad Request
   > Content-Type: application/json
   > content-length: 108
   >
   > {
   >   "jsonrpc" : "2.0",
   >   "id" : 1,
   >   "error" : {
   >     "code" : -32602,
   >     "message" : "Invalid params"
   >   }
   > }

5. `curl -i -X POST --data '{"jsonrpc":"2.0","method":"eth_getBalance","params":null,"id":1}' 127.0.0.1:8545` 

   > HTTP/1.1 400 Bad Request
   > Content-Type: application/json
   > content-length: 108
   >
   > {
   >   "jsonrpc" : "2.0",
   >   "id" : 1,
   >   "error" : {
   >     "code" : -32602,
   >     "message" : "Invalid params"
   >   }
   > }

6. `curl -i -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":null,"id":1}' 127.0.0.1:8545`

   > HTTP/1.1 400 Bad Request
   > Content-Type: application/json
   > content-length: 108
   >
   > {
   >   "jsonrpc" : "2.0",
   >   "id" : 1,
   >   "error" : {
   >     "code" : -32602,
   >     "message" : "Invalid params"
   >   }
   > }

7. `curl -i -X POST --data '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[null],"id":1}' 127.0.0.1:8545`

   > HTTP/1.1 500 Internal Server Error
   > content-length: 0

**Expected behavior:**

In response to requests from step 2 to step 7 included, the JSON-RPC API should systematically return a *400 Bad Request* containing the message `"Invalid Params"`.

**Actual behavior:**

When parameters are required but not provided by the user, the errors are handled inconsistently depending on which method is being called.

The following table illustrates such behavior:

|                       | **`eth_sendRawTransaction`** |     `eth_estimateGas`     | `eth_getBalance` |
| :-------------------: | :--------------------------: | :-----------------------: | :--------------: |
|   **`"params":[]`**   |       400 Bad Request        |      400 Bad Request      | 400 Bad Request  |
|  **`"params":null`**  |  500 Internal Server Error   |      400 Bad Request      | 400 Bad Request  |
| **`"params":[null]`** |  500 Internal Server Error   | 500 Internal Server Error | 400 Bad Request  |

**Frequency:** 

100%

### Versions 
* Software version: *pantheon/v1.0.0-dev-7ab5f605/linux-x86_64/oracle_openjdk-java-10*
* Java version: *OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.4)*
* OS Name & Version: *Ubuntu 18.04.1 LTS*
* Kernel Version: *4.15.0-45-generic x86_64 GNU/Linux*
* Virtual Machine software & version: *VirtualBox Version 6.0.4 r128413 (Qt5.6.2)*

### Additional Information

**Observation**

This behavior is likely to confuse the users who may erroneously use the JSON primitive `null` in such context. 

All the more since `null` appears to be a valid value when parameters are not required. 

For example: 

`curl -i -X POST --data '{"jsonrpc":"2.0","method":"eth_chainId","params":null,"id":1}' 127.0.0.1:8545`

> HTTP/1.1 200 OK
> Content-Type: application/json
> content-length: 57
>
> {
>   "jsonrpc" : "2.0",
>   "id" : 1,
>   "result" : "0x7e2"
> }

**Testing methodology**

Detected using fuzz testing.

Confirmed and analyzed by manual testing.

**Comment by lucassaldanha** [comment]
Thanks for raising the issue and fixing it!
