### ISSUE TITLE
Windows: "The input line is too long" error

### ISSUE THREAD

**Issue by glethuillier** [PegaSysEng/pantheon#839]
### Description

As a Windows (7, 8.1, or 10) user, I want to be able to install Pantheon in any directory and irrespectively of my username, so that I can run it.

### Acceptance Criteria

- On Windows **Command Prompt (cmd.exe)**, from the directory where the Pantheon binary has been built by user **tester.username** *(or any other username containing at least 15 chars)*, `pantheon -V` returns the current version of Pantheon.
- On Windows **PowerShell**, from the directory where the Pantheon binary has been built by user **tester.username** *(or any other username containing at least 15 chars)*, `./pantheon -V` returns the current version of Pantheon.

### Steps to Reproduce

1. Create a Windows account `tester.username`

2. Install Pantheon in `C:\Users\tester.username\` [using the official documentation](https://docs.pantheon.pegasys.tech/en/latest/Installation/Build-From-Source/#installation-on-windows).

   *(This is the directory that appears by default when starting Git bash)*

3. Start cmd.exe or PowerShell

4. `cd C:\Users\tester.username\pantheon\build\distributions\pantheon-1.0.0-SNAPSHOT\bin`

5. `dir`

   *(This command shall show two files: `pantheon` and `pantheon.bat`)*

6.  cmd.exe: `pantheon -V` or PowerShell: `./pantheon -V`

**Expected behavior:**

The current version of Pantheon is displayed.

Example: 

`C:\Users\tester.username\pantheon\build\distributions\pantheon-1.0.0-SNAPSHOT\bin>pantheon -V`
`pantheon/v1.0.0-dev-a82e91a5/windows-x86_64/oracle-java-1.8`

**Actual behavior:**

An error is displayed:

`C:\Users\tester.username\pantheon\build\distributions\pantheon-1.0.0-SNAPSHOT>bin\pantheon -V`
`The input line is too long.`
`The syntax of the command is incorrect.`

**Frequency:** 

100%

### Versions 

- Software version: *pantheon/v1.0.0-dev-a82e91a5/windows-x86_64/oracle-java-1.8*
- Java version: *Java 1.8.0_202*
- OS Name & Version: *Windows 7 Ultimate (64-bit version) / Windows 8.1 Pro (64-bit version) / Windows 10 Enterprise Edition* 
- Virtual Machine software & version: *VirtualBox Version 6.0.4 r128413 (Qt5.6.2)*

### Additional Information

**Observation**

On Windows 7, 8.1, or 10, the command line prompt is limited to 8191 characters ([source](https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation)).

After installation, `pantheon.bat` contains a variable CLASSPATH that contains more than 3000 chars *(line 66)*. 

> set CLASSPATH=%APP_HOME%\lib\pantheon-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-clique-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-ibftlegacy-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-ibft-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-consensus-common-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-json-rpc-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-blockcreation-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-eth-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-p2p-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-core-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-config-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-trie-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-crypto-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-permissioning-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-ethereum-rlp-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-kvstore-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-queue-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\services-util-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-metrics-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\enclave-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\pantheon-util-1.0.0-SNAPSHOT.jar;%APP_HOME%\lib\guava-27.0.1-jre.jar;%APP_HOME%\lib\picocli-3.9.2.jar;%APP_HOME%\lib\vertx-web-3.6.3.jar;%APP_HOME%\lib\vertx-auth-jwt-3.6.2.jar;%APP_HOME%\lib\vertx-web-common-3.6.3.jar;%APP_HOME%\lib\vertx-auth-common-3.6.3.jar;%APP_HOME%\lib\vertx-jwt-3.6.2.jar;%APP_HOME%\lib\vertx-core-3.6.3.jar;%APP_HOME%\lib\cava-toml-0.5.0.jar;%APP_HOME%\lib\log4j-core-2.11.1.jar;%APP_HOME%\lib\log4j-api-2.11.1.jar;%APP_HOME%\lib\spring-security-crypto-5.1.3.RELEASE.jar;%APP_HOME%\lib\jackson-databind-2.9.8.jar;%APP_HOME%\lib\bcprov-jdk15on-1.60.jar;%APP_HOME%\lib\simpleclient_pushgateway-0.6.0.jar;%APP_HOME%\lib\simpleclient_common-0.6.0.jar;%APP_HOME%\lib\simpleclient_hotspot-0.6.0.jar;%APP_HOME%\lib\simpleclient-0.6.0.jar;%APP_HOME%\lib\snappy-java-1.1.7.2.jar;%APP_HOME%\lib\okhttp-3.12.1.jar;%APP_HOME%\lib\rocksdbjni-5.17.2.jar;%APP_HOME%\lib\failureaccess-1.0.1.jar;%APP_HOME%\lib\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;%APP_HOME%\lib\jsr305-3.0.2.jar;%APP_HOME%\lib\checker-qual-2.5.2.jar;%APP_HOME%\lib\error_prone_annotations-2.2.0.jar;%APP_HOME%\lib\j2objc-annotations-1.1.jar;%APP_HOME%\lib\animal-sniffer-annotations-1.17.jar;%APP_HOME%\lib\netty-codec-http2-4.1.30.Final.jar;%APP_HOME%\lib\netty-handler-4.1.30.Final.jar;%APP_HOME%\lib\netty-handler-proxy-4.1.30.Final.jar;%APP_HOME%\lib\netty-resolver-dns-4.1.30.Final.jar;%APP_HOME%\lib\netty-codec-http-4.1.30.Final.jar;%APP_HOME%\lib\netty-codec-socks-4.1.30.Final.jar;%APP_HOME%\lib\netty-codec-dns-4.1.30.Final.jar;%APP_HOME%\lib\netty-codec-4.1.30.Final.jar;%APP_HOME%\lib\netty-transport-4.1.30.Final.jar;%APP_HOME%\lib\netty-buffer-4.1.30.Final.jar;%APP_HOME%\lib\netty-resolver-4.1.30.Final.jar;%APP_HOME%\lib\netty-common-4.1.30.Final.jar;%APP_HOME%\lib\jackson-core-2.9.8.jar;%APP_HOME%\lib\vertx-bridge-common-3.6.3.jar;%APP_HOME%\lib\antlr4-runtime-4.7.1.jar;%APP_HOME%\lib\jackson-annotations-2.9.0.jar;%APP_HOME%\lib\okio-1.15.0.jar

It also contains 67 instances of `%APP_HOME%` that, each, are expanding to the full path to the directory containing Pantheon *(lines 11-14)*.

This variable is in turn expanded when Pantheon is executed: `"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %PANTHEON_OPTS%  -classpath "%CLASSPATH%" tech.pegasys.pantheon.Pantheon %CMD_LINE_ARGS%` *(line 69)*

Under these circumstances, the 8191 characters limit is exceeded.

More precisely, taking into consideration that the syntax of the current path to the binary is `<prefix>\pantheon\build\distributions\pantheon-1.0.0-SNAPSHOT\bin\..`, the error is expected to occur when the `<prefix>` part is 24 char long or longer (e.g. `C:\Users\tester.username`\). 

It can occur with a relatively long username, or when Pantheon is installed into a custom Git local directory (e.g. `C:\Users\Tester\Documents\`).

**Testing methodology**

Tested in 3 VMs containing each a fresh installation of Windows 7, Windows 8.1, and Windows 10 with 64-bit version of JDK/JRE 8u202, Git, and Gradle.

**Comment by ekellstrand** [comment]
Awesome bug report!  I confirm this issue.  Looks like we added a bunch of libraries recently.

As you pointed out, the immediate/quick workaround is to use a shorter directory path, such as moving the installation to c:\pantheon

We'll need to evaluate some options for shortening up the classpath.

**Comment by glethuillier** [comment]
@ekellstrand: Thank you! I am making a short-term fix that will be available in a few hours.
