### ISSUE TITLE
HTTP JSON-RPC: 127.0.0.1 and localhost are handled differently

### ISSUE THREAD

**Issue by glethuillier** [PegaSysEng/pantheon#956]
### Description
As a user of the HTTP JSON-RPC service, I want to be able to locally query this service using `127.0.0.1` instead of `localhost`, so that I can faithfully follow the official documentation.

### Acceptance Criteria
* `curl -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' 127.0.0.1:8545` returns the starting, current, and highest block

### Steps to Reproduce
1. Run a node with the HTTP JSON-RPC service enabled without any whitelisting option: `./pantheon --rpc-http-enabled`

2. Once the node is started, query it via localhost : `curl -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' localhost:8545`

   *(The service returns the starting, current, and highest block, as expected)*

3. Then, query it via 127.0.0.1: `curl -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' 127.0.0.1:8545` (using the same command [than the one provided by the documentation](https://docs.pantheon.pegasys.tech/en/stable/Getting-Started/Starting-Pantheon/))

**Expected behavior:**

The starting, current, and highest block are returned.

Example: 

```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' 127.0.0.1:8545
{
  "jsonrpc" : "2.0",
  "id" : 1,
  "result" : {
    "startingBlock" : "0x0",
    "currentBlock" : "0x0",
    "highestBlock" : "0x0"
  }
}
```

**Actual behavior:**

An error message is returned:

```
$ curl -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' 127.0.0.1:8545
{"message":"Host not authorized."}
```

**Frequency:** 

100%

### Versions 
* Software version: *pantheon/v1.0.1-dev-7aeada26/linux-x86_64/oracle_openjdk-java-1.8*
* Java version: *Java 1.8.0_191*
* OS Name & Version: *Ubuntu 16.04.5 and Ubuntu 18.10*
* Virtual Machine software & version: *VirtualBox Version 6.0.4 r128413 (Qt5.6.2)*

### Additional Information

**Observation**

The RPC HTTP service [checks is the querying header contains an host that is whitelisted](https://github.com/PegaSysEng/pantheon/blob/10f99e322c5ea5846c14e31d46ae92699158ec85/ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpService.java#L222). 

By default, the whitelist contains only one entry: ["localhost"](https://github.com/PegaSysEng/pantheon/blob/6015643a20c0f2875927ac1773d5145fa2950924/ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcConfiguration.java#L32) while the variable `DEFAULT_JSON_RPC_HOST` is set to ["127.0.0.1"](https://github.com/PegaSysEng/pantheon/blob/6015643a20c0f2875927ac1773d5145fa2950924/ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcConfiguration.java#L24).

The whitelist verification [is purely based on a string pattern matching logic](https://github.com/PegaSysEng/pantheon/blob/10f99e322c5ea5846c14e31d46ae92699158ec85/ethereum/jsonrpc/src/main/java/tech/pegasys/pantheon/ethereum/jsonrpc/JsonRpcHttpService.java#L251-L254): therefore, programmatically at least, localhost differs from 127.0.0.1 because they are different strings.

**Contents of `/etc/hosts`**

```shell
127.0.0.1       localhost
127.0.1.1       guillaume-VirtualBox

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**`curl --trace-ascii -`**

```shell
$ curl --trace-ascii - --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}' 127.0.0.1:8545
== Info: Rebuilt URL to: 127.0.0.1:8545/
== Info:   Trying 127.0.0.1...
== Info: TCP_NODELAY set
== Info: Connected to 127.0.0.1 (127.0.0.1) port 8545 (#0)
=> Send header, 148 bytes (0x94)
0000: POST / HTTP/1.1
0011: Host: 127.0.0.1:8545
0027: User-Agent: curl/7.61.0
0040: Accept: */*
004d: Content-Length: 59
0061: Content-Type: application/x-www-form-urlencoded
0092: 
=> Send data, 59 bytes (0x3b)
0000: {"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}
== Info: upload completely sent off: 59 out of 59 bytes
<= Recv header, 24 bytes (0x18)
0000: HTTP/1.1 403 Forbidden
<= Recv header, 47 bytes (0x2f)
0000: Content-Type: application/json; charset=utf-8
<= Recv header, 20 bytes (0x14)
0000: content-length: 34
<= Recv header, 2 bytes (0x2)
0000: 
<= Recv data, 34 bytes (0x22)
0000: {"message":"Host not authorized."}
{"message":"Host not authorized."}== Info: Connection #0 to host 127.0.0.1 left intact
```

**Testing methodology**

Tested in 2 VMs containing each a fresh installation of Ubuntu 16.04.5 and Ubuntu 18.10 with 64-bit version of JDK/JRE, Git, and Gradle.

**Comment by arash009** [comment]
@glethuillier thank you for raising this issue.

This has now been fixed by #974 . Please get the latest release of Pantheon and let us know if you experience any further issues.

**Comment by glethuillier** [comment]
@arash009: Great, I will test it today.

**Comment by glethuillier** [comment]
Successfully tested on Ubuntu 16.04.5 and Ubuntu 18.10. 

Version tested: `pantheon/v1.0.1-dev-01a1dce1/linux-x86_64/oracle_openjdk-java-1.8`
`

**Comment by arash009** [comment]
Awesome, glad to hear. Closing this issue now then.
