### ISSUE TITLE
IBFT node start gets a null error

### ISSUE THREAD

**Issue by carlosfaria94** [PegaSysEng/pantheon#958]
### Description
As a user, I want to run a bootnode in a IBFT network configuration inside a Docker container so that I can connect other nodes on the same network, with the same genesis.

### Acceptance Criteria
* Run a bootnode inside a *Docker container* with a given `genesis.json` and `key` mounted as `volumes`

### Steps to Reproduce (Bug)
1. Use `poa-generator` script to generate the _key_, _ENode_ and _address_ for 4 nodes in a IBFT network 
https://files.gitter.im/PegaSysEng/pantheon/OXVk/poa_generator.tar.gz
2. Create a `docker-compose.yml`:
```
version: '3.2'
services:
  node_0:
    image: pegasyseng/pantheon:1.0.0-RC1
    command: ["--bootnodes",
              "--rpc-http-enabled",
              "--rpc-http-cors-origins=*",
              "--host-whitelist=*",
              "--rpc-http-api=ETH,NET,WEB3,ADMIN,IBFT",
              "--logging=ALL"]
    volumes:
      - type: bind
        source: ./nodes/node_0/key
        target: /var/lib/pantheon/key
      - type: bind
        source: ./nodes/genesis.json
        target: /etc/pantheon/genesis.json
    ports:
      - target: 30303
        published: 30303
        protocol: tcp
        mode: host
      - target: 30303
        published: 30303
        protocol: udp
        mode: host
      - "8545:8545"
```
- `./nodes/node_0/key` is the key created for the first node using the `poa-generator`
- Genesis located on `./nodes/genesis.json`
```
{
  "config": {
    "chainId": 2019,
    "constantinoplefixblock": 0,
    "ibft2": {
      "blockperiodseconds": 2,
      "epochlength": 30000,
      "requesttimeoutseconds": 10
    }
  },
  "coinbase": "0x0000000000000000000000000000000000000000",
  "nonce": "0x0",
  "extraData": "f87ea00000000000000000000000000000000000000000000000000000000000000000f854949cc605687a88a1a1286b11c003ec73547a3129bc94cee41ffc1a7129acc20092b729ec627486aab09b94b8804032ed8d18cae7bb1fb8846ea36df7f251b494d57f3f61125352fad9ba737f3f5e232d882b140c808400000000c0",
  "difficulty": "0x1",
  "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
  "number": "0x0",
  "gasLimit": "0x1000000",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}
```
3. `docker-compose -f docker-compose.yml up node_0`

**Expected behavior:**

A normal node start with the IBFT genesis.

**Actual behavior:** 

`null` error.

```
node_0_1  | Setting logging level to ALL
node_0_1  | 2019-02-25 13:36:51.271+00:00 | main | WARN  | Pantheon | --rpc-ws-host and --rpc-ws-port will have no effect unless --rpc-ws-enabled is defined on the command line.
node_0_1  | 2019-02-25 13:36:52.631+00:00 | main | INFO  | KeyPairUtil | Loaded key 0x25d558c40b2526c253673914af6eb0b7e83ced2cf6b862350317d56cf75d1d4d6876bfd859f8e87a4c2da95d4a3dd9364702e452f34efe99a080fcbebe87e495 from /var/lib/pantheon/key
node_0_1  | 2019-02-25 13:36:53.222+00:00 | main | INFO  | ProtocolScheduleBuilder | Protocol schedule created with milestones: [ConstantinopleFix: 0]
node_0_1  | null
node_0_1  | Usage:
node_0_1  |
node_0_1  | pantheon [OPTIONS] [COMMAND]
node_0_1  |
node_0_1  | Description:
...
node_0_1  | Pantheon is licensed under the Apache License 2.0
ibft_node_0_1 exited with code 1
```

**Frequency:** 100%

### Versions (Add all that apply)

Docker image: `pegasyseng/pantheon:1.0.0-RC1`

**Comment by shemnon** [comment]
Here's the stacktrace that's getting swallowed:

node_0_1  | picocli.CommandLine$ParameterException
node_0_1  | 	at tech.pegasys.pantheon.cli.PantheonCommand.run(PantheonCommand.java:576)
node_0_1  | 	at picocli.CommandLine.execute(CommandLine.java:1160)
node_0_1  | 	at picocli.CommandLine.access$800(CommandLine.java:141)
node_0_1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:1367)
node_0_1  | 	at picocli.CommandLine$RunLast.handle(CommandLine.java:1335)
node_0_1  | 	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
node_0_1  | 	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
node_0_1  | 	at tech.pegasys.pantheon.cli.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:70)
node_0_1  | 	at tech.pegasys.pantheon.cli.ConfigOptionSearchAndRunHandler.handle(ConfigOptionSearchAndRunHandler.java:26)
node_0_1  | 	at picocli.CommandLine$AbstractParseResultHandler.handleParseResult(CommandLine.java:1243)
node_0_1  | 	at picocli.CommandLine.parseWithHandlers(CommandLine.java:1526)
node_0_1  | 	at tech.pegasys.pantheon.cli.PantheonCommand.parse(PantheonCommand.java:507)
node_0_1  | 	at tech.pegasys.pantheon.Pantheon.main(Pantheon.java:39)

**Comment by shemnon** [comment]
You have no allocaitons in your genesis file.  adding "alloc": {} anywhere at the root should fix it.

```
{
    "config": {
      "chainId": 2019,
      "constantinoplefixblock": 0,
      "ibft2": {
        "blockperiodseconds": 2,
        "epochlength": 30000,
        "requesttimeoutseconds": 10
      }
    },
    "coinbase": "0x0000000000000000000000000000000000000000",
    "nonce": "0x0",
    "extraData": "f87ea00000000000000000000000000000000000000000000000000000000000000000f854949cc605687a88a1a1286b11c003ec73547a3129bc94cee41ffc1a7129acc20092b729ec627486aab09b94b8804032ed8d18cae7bb1fb8846ea36df7f251b494d57f3f61125352fad9ba737f3f5e232d882b140c808400000000c0",
    "difficulty": "0x1",
    "mixHash": "0x63746963616c2062797a616e74696e65206661756c7420746f6c6572616e6365",
    "number": "0x0",
    "gasLimit": "0x1000000",
    "gasUsed": "0x0",
    "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "alloc": {}
  }
```

**Comment by carlosfaria94** [comment]
Yes. Adding `"alloc": {}` solves the problem.

Probably in https://docs.pantheon.pegasys.tech/en/latest/Consensus-Protocols/IBFT/ will be a good ideia to put a full genesis example instead of a stripped one.
