### ISSUE TITLE
Update PantheonCommand to accept minTransactionGasPriceWei as an integer (not Wei)

### ISSUE THREAD

**Issue by timbeiko** [PegaSysEng/pantheon#959]
### Description
Because said option has a custom converter, it is read as a string (not integer) - thus it is required to have quotes around it (but maybe only in TOML?).

To resolve this discrepancy and make it simpler, the arg could be converted to accept an integer, the registered convert removed, and the conversion from int --> Wei executed during the construction of MiningParams.

### Additional information
@rain-on I copied this over from JIRA from a ticket you created. Could you please add any missing details? Thanks!

**Comment by arash009** [comment]
This issue is moved to [Jira](https://pegasys1.atlassian.net/browse/PAN-2076) for tracking. Closing in Github.
